import type { Scene, Clip, Layer, MediaSegment, StudioPreset } from '@/types/studio';
import React from 'react';

export type { MediaSegment, Clip, Layer, Scene, StudioPreset };

export interface VideoStudioContextValue {
    title: string;
    setTitle: (v: string) => void;
    format: '9:16' | '16:9';
    setFormat: (v: '9:16' | '16:9') => void;
    scriptLang: string;
    setScriptLang: (v: string) => void;
    newsFocus: string;
    setNewsFocus: (v: string) => void;
    targetDuration: number;
    setTargetDuration: (v: number) => void;
    currentPhase: number;
    setCurrentPhase: (v: number) => void;
    studioStep: 'scenes' | 'editor' | 'export';
    setStudioStep: (v: 'scenes' | 'editor' | 'export') => void;
    error: string | null;
    setError: (v: string | null) => void;
    isLoaded: boolean;
    scenes: Scene[];
    setScenes: React.Dispatch<React.SetStateAction<Scene[]>>;
    updateScene: (index: number, updates: Partial<Scene>) => void;
    videoTrack?: Clip[];
    audioTrack?: Clip[];
    musicTrack?: Clip[];
    overlayTrack?: Clip[];
    layers: Layer[];
    setLayers: React.Dispatch<React.SetStateAction<Layer[]>>;
    addLayer: () => void;
    removeLayer: (id: string) => void;
    reorderLayers: (newOrder: string[]) => void;
    durationInFrames: number;
    setDurationInFrames: (v: number) => void;
    selectedVoice: string;
    setSelectedVoice: (v: string) => void;
    customVoiceUrl?: string;
    setCustomVoiceUrl: (v: string | undefined) => void;
    bgMusicUrl?: string;
    setBgMusicUrl: (v: string | undefined) => void;
    bgMusicVolume: number;
    setBgMusicVolume: (v: number) => void;
    transitionSfxUrl?: string;
    setTransitionSfxUrl: (v: string | undefined) => void;
    introSfxUrl?: string;
    setIntroSfxUrl: (v: string | undefined) => void;
    outroSfxUrl?: string;
    setOutroSfxUrl: (v: string | undefined) => void;
    newsCardSfxUrl?: string;
    setNewsCardSfxUrl: (v: string | undefined) => void;
    voiceSpeed: number;
    setVoiceSpeed: (v: number) => void;
    introDuration: number;
    setIntroDuration: (v: number) => void;
    newsCardDuration: number;
    setNewsCardDuration: (v: number) => void;
    outroDuration: number;
    setOutroDuration: (v: number) => void;
    isGeneratingScript: boolean;
    setIsGeneratingScript: (v: boolean) => void;
    isPreparingAssembly: boolean;
    syncEta: number;
    prepareAssemblyData: () => Promise<void>;
    isGeneratingVideo: boolean;
    setIsGeneratingVideo: (v: boolean) => void;
    renderProgress: number;
    renderStep: string;
    renderEta: number;
    videoUrl: string | null;
    renderFinished: boolean;
    setRenderFinished: (v: boolean) => void;
    setVideoUrl: (v: string | null) => void;
    renderVideo: () => Promise<void>;
    handleDownload: () => void;
    isPlayingPreview: boolean;
    setIsPlayingPreview: (v: boolean) => void;
    exportSettings: {
        resolution: '720p' | '1080p' | '4k';
        quality: 'draft' | 'balanced' | 'max';
        speed: 'fast' | 'medium' | 'slow';
        fps: '24' | '30' | '60';
        outputFormat: 'mp4' | 'webm' | 'mov';
    };
    setExportSettings: (v: any) => void;
    addClip: (layerId: string, clip: Partial<Clip>) => void;
    updateClip: (clipId: string, updates: Partial<Clip>) => void;
    deleteClip: (clipId: string) => void;
    splitClip: (clipId: string, frame: number) => void;
    moveClip: (clipId: string, direction: 'left' | 'right') => void;
    undo: () => void;
    redo: () => void;
    canUndo: boolean;
    canRedo: boolean;
    resetProject: () => void;
    agentMessages: any[];
    setAgentMessages: React.Dispatch<React.SetStateAction<any[]>>;
    isAssetPickerOpen: boolean;
    setIsAssetPickerOpen: (v: boolean) => void;
    activePickerTarget?: string;
    setActivePickerTarget: (v: string | undefined) => void;
    agentThreadId?: string;
    setAgentThreadId: (v: string | undefined) => void;
}
