// Re-export canonical types from types/studio.ts
export type { MediaSegment, Clip, Layer, Scene } from '@/types/studio';

export interface VideoStudioContextValue {
    title: string;
    setTitle: (v: string) => void;
    format: '9:16' | '16:9';
    setFormat: (v: '9:16' | '16:9') => void;
    scriptLang: string;
    setScriptLang: (v: string) => void;
    newsFocus: string;
    setNewsFocus: (v: string) => void;
    targetDuration: number;
    setTargetDuration: (v: number) => void;
    currentPhase: number;
    setCurrentPhase: (v: number) => void;
    error: string | null;
    setError: (v: string | null) => void;
    isLoaded: boolean;
    scenes: import('@/types/studio').Scene[];
    setScenes: React.Dispatch<React.SetStateAction<import('@/types/studio').Scene[]>>;
    updateScene: (index: number, updates: Partial<import('@/types/studio').Scene>) => void;
    videoTrack?: import('@/types/studio').Clip[];
    audioTrack?: import('@/types/studio').Clip[];
    musicTrack?: import('@/types/studio').Clip[];
    overlayTrack?: import('@/types/studio').Clip[];
    layers: import('@/types/studio').Layer[];
    setLayers: React.Dispatch<React.SetStateAction<import('@/types/studio').Layer[]>>;
    addLayer: () => void;
    removeLayer: (id: string) => void;
    reorderLayers: (newOrder: string[]) => void;
    durationInFrames: number;
    setDurationInFrames: (v: number) => void;
    selectedVoice: string;
    setSelectedVoice: (v: string) => void;
    customVoiceUrl?: string;
    setCustomVoiceUrl: (v: string | undefined) => void;
    bgMusicUrl?: string;
    setBgMusicUrl: (v: string | undefined) => void;
    bgMusicVolume: number;
    setBgMusicVolume: (v: number) => void;
    transitionSfxUrl?: string;
    setTransitionSfxUrl: (v: string | undefined) => void;
    introSfxUrl?: string;
    setIntroSfxUrl: (v: string | undefined) => void;
    outroSfxUrl?: string;
    setOutroSfxUrl: (v: string | undefined) => void;
    newsCardSfxUrl?: string;
    setNewsCardSfxUrl: (v: string | undefined) => void;
    voiceSpeed: number;
    setVoiceSpeed: (v: number) => void;
    isGeneratingScript: boolean;
    setIsGeneratingScript: (v: boolean) => void;
    isPreparingAssembly: boolean;
    syncEta: number;
    prepareAssemblyData: () => Promise<void>;
    isGeneratingVideo: boolean;
    setIsGeneratingVideo: (v: boolean) => void;
    renderProgress: number;
    renderStep: string;
    renderEta: number;
    videoUrl: string | null;
    renderFinished: boolean;
    setRenderFinished: (v: boolean) => void;
    setVideoUrl: (v: string | null) => void;
    renderVideo: () => Promise<void>;
    handleDownload: () => void;
    isPlayingPreview: boolean;
    setIsPlayingPreview: (v: boolean) => void;
    exportSettings: {
        resolution: '720p' | '1080p' | '4k';
        quality: 'draft' | 'balanced' | 'max';
        speed: 'fast' | 'medium' | 'slow';
        fps: '24' | '30' | '60';
        outputFormat: 'mp4' | 'webm' | 'mov';
    };
    setExportSettings: (v: any) => void;
    addClip: (layerId: string, clip: Partial<import('@/types/studio').Clip>) => void;
    updateClip: (clipId: string, updates: Partial<import('@/types/studio').Clip>) => void;
    deleteClip: (clipId: string) => void;
    splitClip: (clipId: string, frame: number) => void;
    moveClip: (clipId: string, direction: 'left' | 'right') => void;
    undo: () => void;
    redo: () => void;
    canUndo: boolean;
    canRedo: boolean;
    resetProject: () => void;
}
